---
# tasks file for 017-firewall-disable

- name: Stop and Disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: firewall_status == "inactive"

- name: Start and Enable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_status == "active"
