---
# tasks file for 053-firewall-ops

- name: Start and Enable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_state == "enabled"

- name: Stop and Disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: firewall_state == "disabled"