---
# tasks file for /links/ansible_roles/linux-os-build/065-files-creation

- name: Files Creation on Localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: 0775
  with_items: "{{ files_to_create }}"
  when: where_to == 'local-host'
  delegate_to: localhost


- name: Files Creation on Managed Nodes
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: 0775
  with_items: "{{ files_to_create }}"
  when: where_to == 'all-hosts'