---
# tasks file for 055-root-enable

- name: Remove Config Related to Disable Root Acocunt
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: absent
    backup: yes

- name: Enable ROOT Account via SSH
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin yes"
    state: present
    backup: yes
  notify:
    - restart ssh
