---
# tasks file for 006-machine-id

- name: Delete Existing Machine-ID
  ansible.builtin.file: 
    path: "{{ item }}"
    state: absent
  with_items: 
    - /etc/machine-id
    - /var/lib/dbus/machine-id
  ignore_errors: true
  when: "ansible_nodename !=  sysinfo['servername']"
  

- name: Setting New Machine-ID
  ansible.builtin.shell:
    cmd: systemd-machine-id-setup
  when: "ansible_nodename != sysinfo['servername']"