sysinfo:

    servername: 'vbfedhub01'
    timezone_location: 'Asia/Singapore'
    fqdn_suffix: '.orktion.net'

host_octet: '232'

interfaces:

  - name: natted
    default_route: 'False'
    interface_name: 'enp0s3'
    ip: '10.10.4.{{ host_octet }}' 
    subnet: '24'
    gateway: '10.10.4.1'
    dns1: '10.10.4.1'
    dns2: '4.2.2.2'


  - name: bridged
    default_route: 'False'
    interface_name: 'enp0s8'
    ip: '192.168.1.{{ host_octet }}' 
    subnet: '24'
    gateway: '192.168.1.254'
    dns1: '192.168.1.254'
    dns2: '4.2.2.2'

dateandtime:

    linetodelete: '^pool 2\.fedora\.pool\.ntp\.org iburst$'
    linetoadd: 'server time.google.com iburst'
    timezone_location: 'Asia/Singapore'