---
# tasks file for roles/wait-for-ssh

- name: Wait for Previous Task to Finish
  ansible.builtin.shell:  
    cmd: sleep 60
  delegate_to: localhost

- name: Wait for SSH Action
  local_action:                # Similar to delegate_to: localhost
    module: wait_for
    host: "{{ ansible_host }}"
    port: 22
    delay: 60
    state: started
  register: server_responding

- name: Display Register Value
  ansible.builtin.debug:
    msg: "{{ server_responding }}"