---
# tasks file for /links/ansible_roles/linux-os-hardening/005-nftables

- name: Remove IPTABLES If Exists
  ansible.builtin.dnf:
    name: iptables
    state: absent
  
- name: Ensure Nftables in Installed
  ansible.builitn.dnf:
    name: nftables
    state: present

- name: Ensure Nftables Service is Running
  ansible.builtin.systemd:
    name: nftables
    enabled: yes
    state: started

- name: Copy the Basic NFTABLE Configuration File
  ansible.builtin.copy:
    path: nftables.conf
    dest: /etc/sysconfig/nftables.conf
    owner: root
    group: root
    mode: '0600'