---
# tasks file for ../../00_roles/linux-os-hardening/059-set-dir-perms

- name: Set Direcotry Permissions
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: '/etc/cron.d', mode: '0600', owner: 'root', group: 'root'}
    - { path: '/etc/cron.monthly', mode: '0600', owner: 'root', group: 'root'}
    - { path: '/etc/cron.weekly', mode: '0600', owner: 'root', group: 'root'}
    - { path: '/etc/cron.daily', mode: '0600', owner: 'root', group: 'root'}
    - { path: '/etc/cron.hourly', mode: '0600', owner: 'root', group: 'root'}

