---
# tasks file for /links/ansible_roles/lab-environment/020-vm-shared-folders

- name: Mount the Shared Folders on VMWare Workstation
  ansible.posix.mount:
    path: /storage
    src: .host:/ 
    fstype: fuse.vmhgfs-fuse 
    opts: allow_other
    state: mounted
  when: ansible_virtualization_type == "VMware"